# Задание 2.1 - Нейронные сети

В этом задании вы реализуете и натренируете настоящую нейроную сеть своими руками!

В некотором смысле это будет расширением прошлого задания - нам нужно просто составить несколько линейных классификаторов вместе!

<img src="https://i.redd.it/n9fgba8b0qr01.png" alt="Stack_more_layers" width="400px"/>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

%load_ext autoreload
%autoreload 2

In [2]:
from dataset import load_svhn, random_split_train_val
from gradient_check import check_layer_gradient, check_layer_param_gradient, check_model_gradient
from layers import FullyConnectedLayer, ReLULayer
from model import TwoLayerNet
from trainer import Trainer, Dataset
from optim import SGD, MomentumSGD
from metrics import multiclass_accuracy

# Загружаем данные

И разделяем их на training и validation.

In [3]:
def prepare_for_neural_network(train_X, test_X):
    train_flat = train_X.reshape(train_X.shape[0], -1).astype(np.float) / 255.0
    test_flat = test_X.reshape(test_X.shape[0], -1).astype(np.float) / 255.0
    
    # Subtract mean
    mean_image = np.mean(train_flat, axis = 0)
    train_flat -= mean_image
    test_flat -= mean_image
    
    return train_flat, test_flat
    
train_X, train_y, test_X, test_y = load_svhn("data", max_train=10000, max_test=1000)    
train_X, test_X = prepare_for_neural_network(train_X, test_X)
# Split train into train and val
train_X, train_y, val_X, val_y = random_split_train_val(train_X, train_y, num_val = 1000)

# Как всегда, начинаем с кирпичиков

Мы будем реализовывать необходимые нам слои по очереди. Каждый слой должен реализовать:
- прямой проход (forward pass), который генерирует выход слоя по входу и запоминает необходимые данные
- обратный проход (backward pass), который получает градиент по выходу слоя и вычисляет градиент по входу и по параметрам

Начнем с ReLU, у которого параметров нет.

In [4]:
# TODO: Implement ReLULayer layer in layers.py
# Note: you'll need to copy implementation of the gradient_check function from the previous assignment

X = np.array([[1,-2,3],
              [-1, 2, 0.1]
              ])

assert check_layer_gradient(ReLULayer(), X)

Gradient check passed!


А теперь реализуем полносвязный слой (fully connected layer), у которого будет два массива параметров: W (weights) и B (bias).

Все параметры наши слои будут использовать для параметров специальный класс `Param`, в котором будут храниться значения параметров и градиенты этих параметров, вычисляемые во время обратного прохода.

Это даст возможность аккумулировать (суммировать) градиенты из разных частей функции потерь, например, из cross-entropy loss и regularization loss.

In [5]:
# TODO: Implement FullyConnected layer forward and backward methods
assert check_layer_gradient(FullyConnectedLayer(3, 4), X)
# TODO: Implement storing gradients for W and B
assert check_layer_param_gradient(FullyConnectedLayer(3, 4), X, 'W')
assert check_layer_param_gradient(FullyConnectedLayer(3, 4), X, 'B')

Gradient check passed!
Gradient check passed!
Gradient check passed!


## Создаем нейронную сеть

Теперь мы реализуем простейшую нейронную сеть с двумя полносвязным слоями и нелинейностью ReLU. Реализуйте функцию `compute_loss_and_gradients`, она должна запустить прямой и обратный проход через оба слоя для вычисления градиентов.

Не забудьте реализовать очистку градиентов в начале функции.

In [6]:
# TODO: In model.py, implement compute_loss_and_gradients function
model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 3, reg = 0)
loss = model.compute_loss_and_gradients(train_X[:2], train_y[:2])
# TODO Now implement backward pass and aggregate all of the params
check_model_gradient(model, train_X[:2], train_y[:2])

Checking gradient for W1
Gradient check passed!
Checking gradient for W2
Gradient check passed!
Checking gradient for B1
Gradient check passed!
Checking gradient for B2
Gradient check passed!


True

Теперь добавьте к модели регуляризацию - она должна прибавляться к loss и делать свой вклад в градиенты.

In [7]:
# TODO Now implement l2 regularization in the forward and backward pass
model_with_reg = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 3, reg = 1e1)
loss_with_reg = model_with_reg.compute_loss_and_gradients(train_X[:2], train_y[:2])
assert loss_with_reg > loss and not np.isclose(loss_with_reg, loss), \
    "Loss with regularization (%2.4f) should be higher than without it (%2.4f)!" % (loss, loss_with_reg)

check_model_gradient(model_with_reg, train_X[:2], train_y[:2])

Checking gradient for W1
Gradient check passed!
Checking gradient for W2
Gradient check passed!
Checking gradient for B1
Gradient check passed!
Checking gradient for B2
Gradient check passed!


True

Также реализуем функцию предсказания (вычисления значения) модели на новых данных.

Какое значение точности мы ожидаем увидеть до начала тренировки?

In [12]:
# Finally, implement predict function!

# TODO: Implement predict function
# What would be the value we expect?
multiclass_accuracy(model_with_reg.predict(train_X[:30]), train_y[:30]) 

array([6, 9, 6, 4, 6, 4, 9, 9, 9, 8, 5, 6, 9, 9, 6, 9, 9, 4, 4, 8, 9, 6,
       6, 6, 9, 4, 6, 2, 5, 6], dtype=int64)

0.16666666666666663

# Допишем код для процесса тренировки

In [11]:
model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 100, reg = 1e1)
dataset = Dataset(train_X, train_y, val_X, val_y)
trainer = Trainer(model, dataset, SGD())

# TODO Implement missing pieces in Trainer.fit function
# You should expect loss to go down and train and val accuracy go up for every epoch
loss_history, train_history, val_history = trainer.fit()

array([5, 4, 2, 7, 9, 0, 5, 3, 2, 7, 3, 2, 7, 7, 6, 5, 2, 1, 9, 2],
      dtype=int64)

array([2, 2, 1, 2, 7, 9, 2, 0, 6, 6, 7, 2, 0, 4, 2, 7, 1, 6, 2, 9],
      dtype=int64)

array([6, 9, 2, 9, 0, 7, 1, 0, 2, 9, 2, 7, 2, 2, 6, 9, 2, 6, 7, 2],
      dtype=int64)

array([1, 7, 7, 9, 2, 0, 8, 7, 5, 2, 9, 1, 0, 7, 3, 2, 9, 5, 4, 7],
      dtype=int64)

array([2, 1, 0, 6, 9, 7, 7, 9, 2, 2, 9, 2, 8, 5, 5, 1, 2, 1, 8, 0],
      dtype=int64)

array([1, 5, 9, 4, 7, 9, 2, 2, 6, 5, 4, 7, 9, 9, 6, 3, 2, 1, 2, 2],
      dtype=int64)

array([6, 9, 0, 4, 2, 2, 9, 8, 9, 9, 9, 2, 5, 2, 9, 5, 9, 2, 9, 2],
      dtype=int64)

array([2, 4, 8, 2, 5, 0, 7, 2, 9, 3, 8, 7, 9, 5, 7, 6, 2, 2, 9, 1],
      dtype=int64)

array([2, 2, 3, 0, 2, 2, 4, 4, 8, 4, 7, 7, 1, 5, 6, 9, 2, 2, 9, 6],
      dtype=int64)

array([1, 1, 6, 1, 9, 8, 2, 7, 1, 1, 6, 9, 2, 9, 8, 9, 7, 3, 3, 9],
      dtype=int64)

array([9, 4, 2, 0, 7, 2, 2, 9, 2, 7, 1, 9, 8, 2, 9, 5, 9, 8, 2, 1],
      dtype=int64)

array([2, 2, 7, 3, 9, 8, 2, 7, 5, 0, 2, 3, 5, 9, 5, 6, 3, 0, 2, 7],
      dtype=int64)

array([2, 6, 2, 2, 2, 7, 7, 9, 9, 0, 7, 7, 0, 9, 2, 9, 4, 5, 2, 0],
      dtype=int64)

array([0, 7, 2, 5, 2, 4, 8, 9, 2, 5, 9, 7, 7, 7, 8, 2, 2, 3, 0, 9],
      dtype=int64)

array([9, 0, 2, 0, 2, 3, 2, 2, 9, 7, 4, 7, 7, 2, 9, 2, 0, 1, 6, 1],
      dtype=int64)

array([9, 8, 6, 9, 9, 1, 6, 8, 9, 2, 5, 9, 2, 7, 7, 2, 0, 9, 0, 2],
      dtype=int64)

array([6, 5, 7, 3, 8, 6, 9, 5, 9, 2, 2, 7, 2, 3, 1, 2, 7, 8, 7, 6],
      dtype=int64)

array([2, 5, 2, 4, 4, 2, 2, 2, 7, 7, 1, 2, 5, 8, 2, 9, 7, 3, 7, 9],
      dtype=int64)

array([6, 6, 5, 9, 8, 2, 6, 0, 0, 9, 9, 6, 2, 2, 2, 1, 7, 2, 8, 4],
      dtype=int64)

array([9, 9, 4, 8, 2, 2, 1, 2, 9, 2, 9, 2, 1, 5, 5, 2, 6, 9, 7, 9],
      dtype=int64)

array([1, 3, 6, 6, 3, 2, 1, 8, 2, 2, 6, 1, 7, 3, 0, 0, 9, 0, 4, 9],
      dtype=int64)

array([9, 5, 7, 2, 6, 3, 1, 4, 1, 2, 4, 7, 2, 7, 8, 6, 2, 0, 2, 9],
      dtype=int64)

array([7, 7, 8, 1, 9, 5, 7, 7, 2, 1, 0, 2, 1, 6, 7, 9, 2, 4, 8, 9],
      dtype=int64)

array([5, 4, 6, 4, 0, 0, 7, 9, 2, 8, 7, 1, 8, 9, 2, 9, 2, 7, 9, 2],
      dtype=int64)

array([9, 9, 1, 9, 7, 7, 2, 3, 0, 9, 2, 0, 2, 9, 4, 0, 2, 8, 2, 9],
      dtype=int64)

array([9, 9, 2, 2, 0, 2, 7, 9, 2, 9, 2, 6, 0, 2, 4, 9, 6, 2, 7, 2],
      dtype=int64)

array([7, 9, 2, 5, 2, 6, 2, 9, 2, 9, 3, 2, 1, 2, 9, 9, 9, 9, 9, 9],
      dtype=int64)

array([9, 4, 2, 5, 0, 0, 4, 2, 7, 1, 1, 2, 8, 1, 9, 4, 3, 6, 2, 2],
      dtype=int64)

array([7, 7, 5, 5, 2, 3, 2, 9, 9, 9, 0, 5, 0, 2, 0, 4, 7, 2, 2, 2],
      dtype=int64)

array([4, 0, 7, 8, 7, 2, 5, 7, 6, 7, 2, 9, 2, 1, 6, 9, 2, 9, 9, 7],
      dtype=int64)

array([2, 6, 2, 7, 2, 1, 9, 1, 5, 7, 9, 2, 9, 2, 0, 9, 0, 6, 2, 5],
      dtype=int64)

array([9, 0, 2, 9, 9, 9, 7, 0, 2, 7, 0, 4, 2, 9, 2, 2, 7, 2, 9, 9],
      dtype=int64)

array([9, 4, 2, 6, 1, 2, 2, 2, 6, 1, 4, 2, 3, 8, 9, 2, 5, 8, 0, 9],
      dtype=int64)

array([3, 2, 8, 2, 5, 7, 2, 7, 0, 2, 2, 9, 8, 2, 1, 6, 2, 8, 9, 9],
      dtype=int64)

array([7, 0, 2, 5, 0, 2, 7, 4, 0, 3, 1, 9, 6, 1, 4, 6, 7, 4, 0, 0],
      dtype=int64)

array([3, 5, 2, 5, 7, 7, 0, 4, 2, 6, 8, 6, 9, 2, 9, 2, 2, 2, 7, 3],
      dtype=int64)

array([4, 2, 2, 9, 7, 7, 7, 0, 9, 5, 9, 2, 2, 2, 9, 5, 2, 8, 9, 0],
      dtype=int64)

array([3, 4, 7, 2, 2, 7, 5, 4, 1, 8, 7, 7, 4, 2, 2, 9, 2, 9, 2, 6],
      dtype=int64)

array([2, 2, 3, 9, 5, 1, 2, 9, 2, 0, 2, 2, 1, 9, 2, 8, 6, 9, 6, 8],
      dtype=int64)

array([2, 9, 7, 2, 7, 7, 1, 9, 9, 1, 9, 2, 7, 4, 0, 2, 0, 7, 2, 9],
      dtype=int64)

array([2, 5, 7, 6, 2, 9, 2, 8, 2, 9, 4, 2, 2, 2, 6, 6, 2, 7, 2, 9],
      dtype=int64)

array([2, 9, 7, 8, 0, 8, 2, 2, 7, 9, 2, 2, 9, 7, 2, 9, 2, 2, 4, 2],
      dtype=int64)

array([3, 0, 2, 9, 2, 2, 8, 7, 7, 4, 3, 9, 2, 6, 9, 1, 5, 2, 8, 7],
      dtype=int64)

array([1, 1, 9, 8, 0, 3, 9, 7, 2, 4, 9, 7, 1, 7, 9, 4, 2, 2, 7, 2],
      dtype=int64)

array([9, 2, 7, 9, 3, 4, 4, 0, 3, 7, 2, 2, 1, 0, 7, 7, 1, 0, 2, 9],
      dtype=int64)

array([2, 2, 2, 7, 0, 6, 2, 7, 7, 2, 9, 7, 2, 5, 9, 2, 9, 1, 4, 9],
      dtype=int64)

array([2, 8, 4, 3, 9, 8, 9, 9, 6, 7, 2, 2, 2, 2, 7, 1, 2, 9, 9, 2],
      dtype=int64)

array([6, 2, 9, 8, 6, 2, 2, 2, 5, 6, 9, 0, 7, 7, 4, 2, 9, 2, 3, 8],
      dtype=int64)

array([2, 2, 5, 9, 5, 2, 8, 2, 0, 6, 1, 4, 9, 2, 7, 3, 2, 1, 3, 4],
      dtype=int64)

array([9, 7, 1, 2, 9, 9, 5, 7, 6, 8, 8, 7, 2, 6, 7, 2, 2, 0, 3, 0],
      dtype=int64)

array([9, 0, 6, 2, 1, 7, 7, 2, 9, 2, 7, 2, 0, 2, 9, 5, 6, 5, 9, 5],
      dtype=int64)

array([1, 2, 2, 3, 5, 2, 4, 9, 1, 6, 7, 4, 7, 0, 2, 5, 4, 9, 9, 2],
      dtype=int64)

array([0, 9, 6, 1, 7, 2, 9, 9, 9, 3, 6, 2, 5, 0, 2, 2, 5, 7, 6, 2],
      dtype=int64)

array([2, 4, 4, 8, 0, 9, 1, 2, 6, 5, 2, 7, 2, 2, 2, 7, 7, 2, 9, 1],
      dtype=int64)

array([0, 4, 2, 7, 2, 2, 9, 9, 4, 2, 9, 0, 7, 6, 8, 9, 4, 3, 7, 9],
      dtype=int64)

array([2, 2, 2, 6, 5, 8, 5, 5, 9, 7, 7, 4, 3, 4, 2, 7, 5, 6, 2, 1],
      dtype=int64)

array([9, 6, 2, 7, 5, 3, 6, 1, 0, 4, 7, 2, 4, 1, 9, 2, 7, 9, 9, 9],
      dtype=int64)

array([2, 2, 9, 2, 7, 5, 2, 1, 6, 7, 7, 4, 3, 0, 0, 3, 7, 2, 0, 2],
      dtype=int64)

array([7, 9, 9, 9, 2, 1, 2, 3, 1, 7, 9, 1, 9, 9, 9, 2, 7, 2, 2, 7],
      dtype=int64)

array([9, 2, 9, 0, 5, 6, 9, 7, 4, 2, 2, 4, 0, 7, 2, 5, 9, 9, 2, 2],
      dtype=int64)

array([5, 1, 8, 3, 2, 9, 5, 9, 7, 7, 2, 0, 6, 2, 9, 4, 7, 2, 5, 1],
      dtype=int64)

array([2, 6, 3, 2, 3, 4, 5, 6, 2, 2, 9, 9, 1, 5, 2, 9, 2, 2, 7, 4],
      dtype=int64)

array([4, 7, 2, 6, 2, 2, 6, 1, 3, 2, 0, 7, 2, 2, 9, 0, 3, 7, 9, 2],
      dtype=int64)

array([7, 7, 9, 1, 3, 8, 2, 1, 9, 2, 6, 0, 2, 7, 2, 0, 2, 2, 8, 9],
      dtype=int64)

array([9, 5, 2, 2, 9, 5, 2, 4, 0, 8, 0, 7, 2, 7, 2, 9, 8, 2, 2, 9],
      dtype=int64)

array([9, 2, 9, 2, 9, 2, 2, 2, 5, 0, 9, 2, 0, 2, 2, 7, 7, 2, 8, 9],
      dtype=int64)

array([3, 2, 2, 7, 3, 8, 1, 1, 4, 6, 1, 2, 6, 9, 4, 8, 2, 8, 2, 2],
      dtype=int64)

array([2, 9, 0, 9, 5, 7, 2, 9, 2, 6, 7, 8, 7, 2, 2, 6, 9, 2, 2, 9],
      dtype=int64)

array([8, 5, 0, 8, 0, 9, 3, 7, 3, 2, 7, 7, 4, 5, 4, 0, 2, 5, 1, 1],
      dtype=int64)

array([9, 4, 2, 9, 8, 2, 6, 2, 2, 8, 2, 7, 4, 7, 3, 3, 0, 0, 2, 6],
      dtype=int64)

array([2, 6, 6, 8, 2, 4, 9, 0, 2, 4, 7, 2, 9, 5, 2, 5, 9, 2, 0, 9],
      dtype=int64)

array([2, 7, 3, 2, 9, 0, 7, 5, 9, 0, 9, 0, 2, 7, 7, 2, 5, 2, 9, 1],
      dtype=int64)

array([2, 2, 9, 1, 5, 7, 2, 2, 2, 2, 7, 9, 9, 0, 9, 9, 9, 9, 6, 1],
      dtype=int64)

array([2, 6, 6, 3, 1, 9, 6, 9, 4, 1, 6, 8, 2, 2, 3, 2, 9, 9, 7, 2],
      dtype=int64)

array([0, 0, 2, 2, 2, 7, 2, 2, 9, 3, 3, 7, 6, 2, 9, 5, 8, 2, 9, 3],
      dtype=int64)

array([2, 9, 0, 3, 9, 9, 6, 2, 6, 1, 2, 3, 4, 7, 2, 2, 9, 3, 2, 7],
      dtype=int64)

array([2, 4, 2, 3, 2, 9, 2, 8, 0, 9, 5, 7, 0, 9, 2, 6, 2, 2, 6, 8],
      dtype=int64)

array([9, 4, 6, 3, 7, 2, 2, 2, 5, 9, 2, 7, 2, 1, 3, 2, 9, 6, 2, 9],
      dtype=int64)

array([7, 2, 5, 2, 1, 7, 4, 4, 6, 2, 5, 0, 9, 9, 1, 2, 9, 2, 2, 9],
      dtype=int64)

array([5, 2, 7, 3, 6, 2, 9, 2, 7, 8, 9, 2, 1, 7, 7, 6, 4, 2, 5, 2],
      dtype=int64)

array([4, 2, 3, 9, 0, 1, 7, 4, 7, 7, 2, 9, 2, 2, 6, 6, 7, 9, 2, 4],
      dtype=int64)

array([6, 1, 1, 9, 9, 7, 3, 2, 1, 0, 9, 0, 7, 9, 5, 1, 8, 9, 2, 4],
      dtype=int64)

array([9, 5, 0, 2, 9, 5, 8, 3, 2, 5, 2, 2, 7, 8, 2, 6, 4, 8, 0, 2],
      dtype=int64)

array([2, 2, 9, 6, 1, 2, 2, 2, 9, 3, 3, 8, 9, 4, 3, 9, 2, 0, 2, 7],
      dtype=int64)

array([8, 2, 9, 9, 2, 9, 5, 4, 1, 2, 9, 3, 9, 6, 5, 0, 6, 2, 7, 2],
      dtype=int64)

array([2, 7, 2, 2, 9, 0, 2, 7, 1, 3, 4, 9, 6, 7, 9, 5, 9, 0, 5, 2],
      dtype=int64)

array([9, 9, 6, 5, 7, 9, 2, 9, 7, 2, 2, 1, 8, 2, 5, 9, 2, 2, 2, 9],
      dtype=int64)

array([2, 0, 5, 5, 7, 9, 7, 9, 1, 9, 6, 7, 5, 5, 1, 9, 1, 0, 9, 5],
      dtype=int64)

array([0, 3, 3, 9, 8, 2, 6, 5, 9, 9, 2, 1, 7, 5, 4, 1, 2, 5, 1, 3],
      dtype=int64)

array([5, 2, 5, 1, 9, 7, 9, 0, 2, 2, 2, 0, 6, 1, 8, 2, 7, 2, 3, 2],
      dtype=int64)

array([1, 0, 4, 2, 2, 7, 2, 8, 7, 4, 9, 2, 7, 9, 2, 0, 2, 2, 7, 9],
      dtype=int64)

array([2, 2, 6, 2, 5, 3, 2, 6, 3, 7, 4, 9, 9, 6, 9, 9, 2, 0, 8, 9],
      dtype=int64)

array([2, 9, 9, 2, 7, 9, 0, 2, 2, 2, 7, 7, 8, 0, 7, 9, 6, 2, 1, 2],
      dtype=int64)

array([2, 7, 7, 9, 9, 6, 7, 3, 2, 9, 2, 2, 9, 0, 3, 9, 7, 2, 9, 2],
      dtype=int64)

array([8, 9, 2, 7, 7, 9, 6, 9, 2, 4, 2, 7, 2, 6, 2, 2, 4, 0, 8, 2],
      dtype=int64)

array([7, 1, 7, 5, 9, 8, 7, 2, 9, 6, 5, 9, 2, 2, 2, 9, 2, 9, 2, 8],
      dtype=int64)

array([2, 2, 8, 2, 2, 2, 7, 1, 9, 0, 9, 8, 4, 2, 2, 2, 9, 0, 5, 3],
      dtype=int64)

array([5, 7, 2, 1, 2, 5, 9, 1, 1, 0, 6, 9, 4, 2, 2, 6, 9, 7, 7, 3],
      dtype=int64)

array([9, 2, 9, 9, 2, 9, 9, 2, 7, 8, 0, 2, 2, 5, 9, 3, 4, 9, 6, 2],
      dtype=int64)

array([7, 1, 2, 0, 2, 7, 5, 9, 9, 1, 4, 2, 9, 8, 2, 3, 9, 8, 2, 6],
      dtype=int64)

array([9, 2, 1, 2, 7, 4, 0, 0, 0, 9, 4, 2, 0, 9, 0, 2, 9, 7, 2, 2],
      dtype=int64)

array([5, 3, 6, 9, 4, 3, 1, 5, 7, 2, 2, 0, 2, 9, 0, 5, 2, 9, 2, 3],
      dtype=int64)

array([2, 9, 6, 6, 5, 3, 0, 9, 9, 2, 9, 6, 2, 3, 7, 1, 8, 2, 2, 9],
      dtype=int64)

array([2, 2, 2, 8, 2, 9, 2, 9, 7, 7, 7, 7, 0, 4, 6, 7, 2, 8, 4, 3],
      dtype=int64)

array([2, 2, 9, 2, 5, 8, 2, 7, 9, 7, 2, 0, 6, 2, 9, 6, 2, 9, 2, 0],
      dtype=int64)

array([6, 9, 2, 5, 0, 3, 2, 2, 2, 8, 9, 2, 2, 3, 6, 7, 4, 0, 7, 2],
      dtype=int64)

array([3, 0, 4, 8, 2, 8, 2, 5, 2, 2, 1, 2, 9, 0, 5, 6, 9, 7, 6, 2],
      dtype=int64)

array([8, 5, 1, 2, 7, 9, 5, 2, 9, 4, 9, 4, 5, 0, 2, 9, 9, 4, 5, 1],
      dtype=int64)

array([1, 5, 0, 1, 3, 6, 0, 1, 4, 0, 0, 7, 0, 2, 2, 2, 9, 9, 6, 8],
      dtype=int64)

array([4, 2, 9, 7, 7, 6, 5, 8, 7, 0, 2, 4, 0, 7, 2, 1, 2, 9, 2, 2],
      dtype=int64)

array([0, 4, 5, 2, 2, 0, 2, 2, 5, 8, 2, 1, 2, 7, 2, 9, 6, 7, 5, 6],
      dtype=int64)

array([2, 5, 2, 3, 0, 9, 2, 9, 2, 0, 2, 2, 5, 8, 7, 2, 4, 0, 1, 7],
      dtype=int64)

array([9, 2, 4, 1, 8, 9, 2, 2, 2, 2, 9, 9, 2, 9, 1, 2, 2, 1, 1, 4],
      dtype=int64)

array([0, 1, 1, 5, 1, 9, 2, 2, 1, 7, 9, 9, 3, 7, 7, 9, 1, 7, 9, 6],
      dtype=int64)

array([6, 8, 8, 3, 8, 4, 9, 7, 7, 4, 9, 4, 2, 2, 9, 7, 6, 2, 7, 2],
      dtype=int64)

array([9, 7, 2, 3, 4, 9, 9, 0, 9, 2, 4, 1, 6, 3, 2, 2, 9, 3, 6, 0],
      dtype=int64)

array([2, 2, 7, 9, 0, 4, 9, 6, 2, 9, 7, 9, 9, 5, 1, 6, 2, 9, 2, 2],
      dtype=int64)

array([2, 3, 7, 8, 9, 2, 2, 1, 2, 0, 2, 2, 3, 4, 9, 9, 4, 4, 6, 8],
      dtype=int64)

array([2, 8, 6, 1, 7, 7, 7, 4, 9, 5, 0, 2, 4, 2, 2, 9, 9, 2, 9, 2],
      dtype=int64)

array([2, 4, 2, 9, 2, 0, 6, 2, 7, 8, 9, 4, 5, 0, 1, 9, 0, 9, 2, 1],
      dtype=int64)

array([4, 2, 3, 2, 0, 2, 6, 9, 7, 3, 1, 3, 0, 4, 6, 3, 2, 7, 5, 8],
      dtype=int64)

array([2, 2, 2, 8, 5, 7, 5, 9, 6, 2, 0, 9, 6, 1, 0, 6, 4, 9, 6, 4],
      dtype=int64)

array([2, 9, 0, 7, 2, 2, 9, 9, 1, 2, 9, 5, 2, 4, 2, 4, 9, 9, 3, 0],
      dtype=int64)

array([6, 6, 9, 2, 7, 0, 2, 9, 5, 4, 8, 2, 4, 2, 2, 9, 2, 9, 7, 7],
      dtype=int64)

array([9, 2, 8, 8, 7, 2, 9, 6, 1, 2, 7, 6, 6, 2, 0, 5, 9, 9, 5, 2],
      dtype=int64)

array([7, 9, 5, 2, 7, 0, 0, 1, 4, 3, 7, 4, 2, 0, 6, 9, 2, 2, 6, 0],
      dtype=int64)

array([7, 4, 3, 9, 0, 2, 7, 1, 2, 6, 2, 9, 2, 9, 4, 9, 0, 1, 3, 2],
      dtype=int64)

array([8, 9, 2, 9, 0, 0, 6, 8, 9, 9, 2, 2, 7, 9, 2, 2, 7, 2, 3, 6],
      dtype=int64)

array([8, 2, 2, 9, 2, 1, 7, 7, 2, 7, 5, 4, 0, 8, 9, 9, 9, 9, 5, 0],
      dtype=int64)

array([5, 9, 2, 9, 2, 2, 2, 2, 6, 7, 4, 9, 0, 7, 7, 9, 2, 2, 7, 3],
      dtype=int64)

array([9, 1, 2, 2, 2, 9, 2, 2, 3, 4, 8, 9, 3, 7, 1, 1, 9, 8, 1, 4],
      dtype=int64)

array([1, 3, 9, 3, 1, 0, 2, 8, 9, 2, 9, 9, 2, 7, 6, 1, 4, 4, 6, 2],
      dtype=int64)

array([2, 0, 4, 8, 2, 6, 2, 9, 8, 3, 9, 2, 1, 6, 1, 4, 2, 2, 7, 2],
      dtype=int64)

array([6, 2, 9, 2, 9, 9, 9, 0, 9, 8, 1, 5, 0, 4, 1, 2, 7, 3, 0, 2],
      dtype=int64)

array([6, 3, 9, 9, 7, 9, 6, 2, 9, 1, 2, 0, 1, 2, 0, 0, 2, 4, 2, 6],
      dtype=int64)

array([5, 2, 2, 9, 7, 7, 7, 8, 6, 9, 0, 7, 2, 2, 7, 7, 6, 2, 2, 9],
      dtype=int64)

array([2, 0, 4, 2, 7, 4, 4, 1, 9, 7, 0, 9, 3, 9, 6, 5, 8, 7, 0, 2],
      dtype=int64)

array([4, 0, 4, 2, 9, 2, 3, 1, 0, 2, 2, 2, 9, 9, 8, 6, 7, 8, 3, 2],
      dtype=int64)

array([2, 4, 7, 7, 9, 2, 9, 2, 3, 9, 4, 7, 9, 2, 2, 2, 0, 6, 0, 2],
      dtype=int64)

array([2, 7, 2, 0, 0, 7, 2, 9, 2, 2, 4, 0, 2, 2, 2, 0, 9, 6, 9, 7],
      dtype=int64)

array([9, 2, 7, 5, 7, 7, 2, 6, 6, 6, 9, 0, 1, 2, 9, 3, 8, 4, 7, 4],
      dtype=int64)

array([3, 5, 0, 2, 1, 4, 2, 7, 9, 7, 9, 1, 3, 7, 9, 5, 7, 1, 4, 4],
      dtype=int64)

array([2, 7, 2, 1, 2, 4, 2, 4, 2, 9, 5, 2, 8, 0, 9, 2, 9, 9, 5, 7],
      dtype=int64)

array([6, 9, 6, 7, 9, 2, 6, 0, 2, 2, 2, 9, 2, 2, 7, 8, 7, 9, 0, 0],
      dtype=int64)

array([7, 4, 1, 2, 5, 5, 4, 2, 9, 8, 9, 9, 9, 9, 2, 2, 9, 2, 6, 9],
      dtype=int64)

array([8, 9, 8, 6, 5, 4, 5, 7, 4, 2, 2, 2, 4, 3, 7, 7, 2, 3, 2, 0],
      dtype=int64)

array([6, 9, 2, 4, 2, 1, 4, 2, 0, 5, 4, 7, 7, 1, 9, 8, 7, 8, 7, 2],
      dtype=int64)

array([4, 2, 2, 2, 2, 5, 2, 0, 7, 1, 9, 2, 7, 1, 9, 9, 2, 6, 0, 7],
      dtype=int64)

array([2, 9, 6, 8, 9, 2, 5, 6, 2, 7, 8, 9, 2, 7, 7, 6, 4, 2, 9, 9],
      dtype=int64)

array([7, 2, 9, 8, 2, 0, 4, 6, 8, 2, 2, 5, 2, 7, 6, 2, 0, 5, 2, 8],
      dtype=int64)

array([2, 7, 5, 2, 6, 2, 6, 3, 2, 6, 2, 3, 9, 9, 2, 0, 7, 0, 7, 6],
      dtype=int64)

array([2, 7, 9, 3, 9, 3, 9, 0, 2, 6, 6, 2, 2, 9, 9, 7, 5, 9, 0, 2],
      dtype=int64)

array([5, 2, 4, 6, 2, 7, 6, 0, 9, 4, 9, 8, 9, 2, 3, 1, 7, 4, 2, 7],
      dtype=int64)

array([9, 2, 4, 0, 6, 7, 0, 5, 0, 2, 3, 2, 2, 8, 2, 9, 2, 0, 2, 8],
      dtype=int64)

array([6, 0, 2, 8, 5, 0, 9, 2, 2, 9, 5, 3, 2, 2, 6, 7, 2, 7, 2, 7],
      dtype=int64)

array([9, 2, 9, 2, 0, 9, 4, 2, 9, 6, 0, 7, 2, 4, 8, 1, 7, 2, 2, 9],
      dtype=int64)

array([4, 8, 2, 2, 5, 0, 2, 7, 7, 5, 2, 3, 7, 9, 8, 9, 3, 0, 4, 2],
      dtype=int64)

array([2, 6, 7, 2, 6, 9, 9, 2, 9, 0, 2, 7, 9, 4, 6, 2, 2, 2, 1, 1],
      dtype=int64)

array([7, 2, 2, 9, 2, 4, 2, 9, 6, 6, 5, 7, 3, 6, 8, 4, 2, 3, 8, 2],
      dtype=int64)

array([2, 9, 0, 7, 2, 9, 0, 2, 2, 1, 2, 7, 2, 0, 9, 2, 2, 7, 3, 2],
      dtype=int64)

array([2, 1, 8, 9, 1, 0, 9, 6, 6, 9, 7, 7, 2, 2, 2, 4, 7, 3, 6, 4],
      dtype=int64)

array([5, 5, 9, 2, 2, 6, 2, 8, 2, 9, 7, 8, 1, 6, 2, 4, 2, 5, 3, 7],
      dtype=int64)

array([3, 8, 5, 1, 2, 9, 2, 9, 2, 7, 7, 3, 7, 2, 9, 2, 9, 2, 6, 8],
      dtype=int64)

array([1, 9, 0, 2, 9, 2, 5, 2, 2, 2, 2, 8, 2, 9, 3, 3, 3, 9, 2, 0],
      dtype=int64)

array([2, 4, 2, 0, 1, 2, 1, 2, 7, 9, 2, 8, 9, 6, 3, 8, 0, 2, 7, 2],
      dtype=int64)

array([7, 9, 2, 2, 7, 7, 3, 5, 9, 4, 9, 2, 1, 9, 2, 6, 6, 1, 4, 8],
      dtype=int64)

array([2, 5, 9, 5, 7, 2, 4, 2, 7, 7, 5, 9, 2, 2, 7, 2, 8, 9, 9, 0],
      dtype=int64)

array([2, 1, 6, 0, 9, 5, 6, 9, 9, 3, 2, 0, 4, 0, 9, 2, 2, 9, 2, 7],
      dtype=int64)

array([2, 1, 5, 2, 2, 6, 2, 1, 6, 3, 6, 2, 5, 7, 9, 7, 5, 9, 5, 2],
      dtype=int64)

array([1, 2, 6, 0, 7, 9, 2, 1, 9, 1, 3, 9, 7, 0, 3, 7, 9, 9, 2, 2],
      dtype=int64)

array([2, 2, 2, 7, 9, 7, 7, 2, 2, 9, 7, 2, 3, 5, 7, 7, 0, 2, 9, 2],
      dtype=int64)

array([1, 2, 7, 0, 7, 7, 5, 1, 6, 9, 2, 2, 8, 9, 2, 2, 4, 7, 9, 5],
      dtype=int64)

array([7, 6, 7, 5, 2, 5, 2, 3, 2, 9, 3, 6, 9, 4, 2, 3, 9, 3, 0, 2],
      dtype=int64)

array([8, 0, 9, 2, 2, 7, 6, 2, 0, 2, 2, 3, 2, 7, 8, 5, 5, 9, 7, 5],
      dtype=int64)

array([2, 8, 5, 2, 6, 2, 7, 7, 2, 9, 2, 9, 5, 9, 9, 8, 7, 7, 2, 2],
      dtype=int64)

array([3, 6, 9, 5, 1, 2, 5, 4, 9, 1, 3, 2, 0, 7, 2, 6, 7, 4, 2, 9],
      dtype=int64)

array([6, 4, 4, 2, 1, 9, 7, 2, 1, 9, 2, 8, 7, 9, 8, 2, 0, 2, 6, 2],
      dtype=int64)

array([2, 9, 2, 9, 0, 7, 0, 3, 2, 9, 1, 9, 7, 9, 1, 0, 2, 2, 9, 8],
      dtype=int64)

array([2, 2, 2, 2, 2, 7, 5, 6, 9, 0, 8, 2, 0, 5, 3, 9, 5, 2, 7, 5],
      dtype=int64)

array([7, 3, 7, 2, 0, 2, 9, 5, 9, 2, 2, 2, 2, 7, 6, 9, 0, 2, 5, 6],
      dtype=int64)

array([2, 5, 7, 9, 2, 1, 4, 9, 9, 3, 0, 0, 2, 5, 1, 3, 9, 5, 7, 2],
      dtype=int64)

array([2, 0, 7, 5, 2, 7, 2, 9, 9, 3, 5, 9, 9, 2, 3, 8, 4, 2, 6, 2],
      dtype=int64)

array([1, 9, 1, 7, 9, 0, 2, 9, 9, 5, 8, 3, 1, 2, 2, 6, 2, 2, 9, 7],
      dtype=int64)

array([4, 2, 2, 0, 0, 6, 8, 6, 2, 4, 9, 3, 7, 2, 4, 9, 2, 7, 5, 7],
      dtype=int64)

array([3, 7, 4, 2, 0, 9, 2, 7, 2, 9, 9, 7, 2, 7, 7, 2, 2, 9, 2, 6],
      dtype=int64)

array([5, 5, 2, 2, 2, 6, 7, 0, 6, 2, 5, 9, 3, 9, 5, 9, 5, 9, 5, 7],
      dtype=int64)

array([5, 2, 2, 7, 3, 2, 2, 9, 7, 7, 5, 6, 3, 9, 1, 7, 2, 9, 6, 0],
      dtype=int64)

array([6, 9, 9, 6, 8, 2, 6, 5, 7, 5, 6, 2, 4, 8, 2, 9, 2, 2, 3, 5],
      dtype=int64)

array([3, 2, 2, 2, 9, 2, 9, 2, 9, 6, 9, 2, 2, 9, 7, 7, 9, 8, 0, 2],
      dtype=int64)

array([7, 9, 2, 7, 8, 0, 6, 0, 9, 7, 2, 2, 0, 3, 2, 5, 6, 2, 2, 2],
      dtype=int64)

array([0, 2, 8, 7, 4, 9, 2, 4, 6, 7, 0, 9, 2, 3, 4, 2, 2, 9, 1, 7],
      dtype=int64)

array([7, 2, 3, 7, 9, 7, 2, 0, 2, 3, 7, 5, 2, 1, 7, 9, 9, 2, 6, 6],
      dtype=int64)

array([2, 5, 2, 2, 9, 9, 6, 7, 6, 8, 0, 7, 9, 2, 7, 2, 7, 9, 2, 6],
      dtype=int64)

array([6, 7, 9, 7, 9, 6, 9, 6, 9, 5, 9, 9, 1, 2, 5, 2, 1, 3, 7, 2],
      dtype=int64)

array([1, 1, 9, 0, 6, 2, 0, 2, 7, 4, 2, 6, 1, 9, 9, 2, 2, 2, 5, 2],
      dtype=int64)

array([2, 9, 2, 3, 2, 0, 8, 6, 6, 2, 2, 8, 7, 0, 7, 0, 2, 9, 9, 2],
      dtype=int64)

array([2, 7, 4, 9, 6, 1, 9, 7, 2, 2, 1, 7, 8, 0, 2, 9, 2, 2, 2, 9],
      dtype=int64)

array([1, 2, 1, 1, 8, 5, 9, 1, 9, 7, 2, 7, 0, 9, 2, 6, 8, 2, 2, 1],
      dtype=int64)

array([5, 2, 2, 2, 8, 2, 2, 0, 9, 6, 7, 5, 9, 3, 7, 9, 7, 9, 9, 7],
      dtype=int64)

array([9, 7, 2, 7, 2, 2, 2, 8, 7, 2, 2, 6, 2, 5, 7, 7, 0, 0, 2, 6],
      dtype=int64)

array([6, 9, 9, 7, 7, 2, 7, 2, 7, 9, 6, 9, 8, 0, 4, 2, 2, 9, 5, 3],
      dtype=int64)

array([1, 2, 7, 2, 9, 7, 9, 6, 4, 6, 6, 5, 5, 7, 9, 2, 6, 5, 5, 2],
      dtype=int64)

array([6, 4, 7, 9, 2, 2, 0, 5, 1, 2, 9, 1, 0, 8, 2, 2, 2, 4, 0, 4],
      dtype=int64)

array([1, 5, 9, 3, 1, 8, 8, 2, 1, 2, 0, 8, 3, 9, 7, 1, 0, 4, 9, 7],
      dtype=int64)

array([2, 6, 0, 2, 2, 0, 0, 0, 7, 2, 5, 6, 2, 2, 3, 5, 8, 4, 7, 8],
      dtype=int64)

array([9, 9, 2, 7, 0, 2, 2, 0, 2, 0, 0, 9, 1, 3, 7, 2, 3, 0, 7, 5],
      dtype=int64)

array([2, 7, 9, 9, 6, 8, 2, 2, 2, 2, 1, 5, 5, 9, 2, 7, 0, 2, 9, 5],
      dtype=int64)

array([9, 8, 0, 9, 2, 5, 4, 4, 9, 2, 2, 1, 9, 4, 8, 8, 3, 3, 7, 7],
      dtype=int64)

array([5, 4, 9, 9, 2, 9, 2, 2, 7, 2, 1, 6, 7, 0, 0, 2, 2, 7, 4, 6],
      dtype=int64)

array([0, 4, 4, 3, 2, 5, 3, 2, 2, 6, 7, 7, 7, 2, 9, 2, 9, 3, 9, 7],
      dtype=int64)

array([1, 8, 9, 9, 8, 0, 9, 9, 2, 1, 9, 9, 9, 1, 5, 2, 5, 1, 1, 7],
      dtype=int64)

array([0, 9, 6, 2, 7, 3, 6, 7, 3, 9, 2, 6, 2, 9, 2, 2, 2, 5, 3, 9],
      dtype=int64)

array([2, 2, 6, 9, 0, 1, 1, 7, 8, 2, 9, 2, 7, 2, 4, 0, 7, 9, 7, 2],
      dtype=int64)

array([2, 6, 6, 7, 0, 2, 4, 0, 2, 9, 2, 5, 2, 1, 7, 7, 1, 2, 7, 5],
      dtype=int64)

array([3, 2, 4, 0, 1, 8, 5, 6, 9, 2, 2, 6, 2, 2, 0, 0, 4, 9, 3, 7],
      dtype=int64)

array([0, 7, 8, 0, 3, 2, 2, 5, 8, 4, 6, 1, 9, 2, 9, 2, 2, 9, 9, 2],
      dtype=int64)

array([2, 7, 9, 9, 2, 2, 0, 2, 9, 1, 2, 1, 2, 7, 7, 6, 7, 9, 5, 4],
      dtype=int64)

array([7, 6, 0, 1, 4, 9, 9, 1, 7, 9, 9, 2, 1, 5, 2, 2, 9, 9, 6, 0],
      dtype=int64)

array([8, 7, 7, 9, 7, 0, 1, 1, 5, 9, 6, 9, 9, 2, 7, 0, 2, 9, 9, 1],
      dtype=int64)

array([6, 4, 9, 4, 2, 2, 1, 0, 2, 5, 6, 3, 1, 9, 6, 1, 0, 2, 3, 9],
      dtype=int64)

array([2, 5, 9, 3, 2, 1, 2, 6, 7, 8, 2, 9, 9, 0, 7, 8, 5, 0, 9, 7],
      dtype=int64)

array([7, 6, 7, 1, 8, 9, 2, 9, 4, 2, 1, 0, 3, 1, 8, 2, 3, 8, 8, 5],
      dtype=int64)

array([6, 7, 5, 4, 7, 8, 2, 9, 2, 2, 9, 7, 4, 2, 2, 1, 0, 6, 0, 0],
      dtype=int64)

array([7, 2, 2, 2, 3, 2, 2, 5, 6, 9, 2, 7, 0, 7, 9, 2, 7, 8, 6, 2],
      dtype=int64)

array([4, 2, 7, 2, 0, 0, 9, 6, 2, 5, 2, 8, 9, 2, 0, 6, 9, 4, 8, 7],
      dtype=int64)

array([8, 3, 6, 6, 8, 6, 2, 9, 6, 5, 2, 2, 9, 6, 2, 9, 2, 6, 2, 1],
      dtype=int64)

array([7, 7, 9, 7, 5, 0, 2, 2, 9, 4, 9, 2, 8, 2, 8, 2, 8, 9, 2, 9],
      dtype=int64)

array([2, 2, 2, 4, 2, 5, 6, 7, 4, 7, 8, 6, 3, 6, 9, 9, 2, 0, 2, 3],
      dtype=int64)

array([2, 9, 9, 2, 2, 9, 2, 9, 6, 2, 8, 2, 2, 7, 1, 0, 7, 6, 9, 4],
      dtype=int64)

array([9, 0, 2, 8, 9, 7, 1, 2, 2, 8, 1, 7, 9, 9, 4, 7, 6, 5, 9, 7],
      dtype=int64)

array([2, 2, 0, 7, 5, 7, 7, 1, 0, 2, 9, 3, 8, 2, 2, 6, 5, 4, 9, 3],
      dtype=int64)

array([9, 0, 8, 2, 3, 8, 6, 9, 4, 0, 2, 2, 1, 2, 9, 9, 0, 6, 7, 2],
      dtype=int64)

array([5, 9, 2, 6, 8, 2, 9, 8, 1, 2, 2, 3, 0, 2, 5, 9, 2, 5, 0, 0],
      dtype=int64)

array([2, 4, 4, 8, 7, 7, 9, 8, 9, 9, 9, 7, 6, 2, 7, 2, 2, 2, 4, 2],
      dtype=int64)

array([1, 9, 9, 2, 9, 7, 7, 2, 9, 9, 3, 0, 1, 7, 2, 7, 2, 4, 2, 9],
      dtype=int64)

array([7, 2, 6, 9, 2, 8, 1, 2, 1, 8, 9, 2, 2, 8, 9, 9, 7, 4, 3, 3],
      dtype=int64)

array([9, 2, 5, 4, 9, 8, 6, 9, 2, 2, 7, 2, 9, 6, 2, 2, 5, 9, 2, 6],
      dtype=int64)

array([9, 5, 3, 2, 0, 2, 9, 2, 2, 0, 7, 3, 9, 5, 6, 2, 4, 9, 4, 2],
      dtype=int64)

array([2, 2, 9, 6, 9, 5, 9, 7, 7, 4, 0, 5, 8, 2, 2, 9, 5, 2, 2, 3],
      dtype=int64)

array([2, 2, 0, 2, 9, 2, 2, 2, 7, 2, 9, 6, 9, 6, 0, 9, 0, 7, 2, 9],
      dtype=int64)

array([9, 9, 9, 2, 6, 2, 7, 1, 6, 2, 0, 7, 6, 9, 2, 2, 0, 2, 9, 4],
      dtype=int64)

array([2, 2, 1, 2, 9, 3, 2, 0, 8, 9, 4, 7, 2, 0, 9, 4, 7, 9, 7, 9],
      dtype=int64)

array([2, 7, 2, 7, 7, 2, 8, 9, 4, 2, 8, 2, 3, 4, 2, 9, 5, 5, 1, 2],
      dtype=int64)

array([0, 2, 0, 8, 1, 2, 9, 2, 2, 0, 7, 5, 2, 6, 2, 7, 7, 1, 2, 9],
      dtype=int64)

array([1, 8, 9, 9, 8, 2, 9, 9, 1, 2, 0, 1, 8, 8, 1, 9, 2, 7, 9, 5],
      dtype=int64)

array([0, 7, 6, 7, 2, 1, 2, 9, 9, 0, 2, 5, 2, 2, 8, 6, 3, 9, 4, 7],
      dtype=int64)

array([2, 2, 2, 7, 6, 2, 7, 9, 2, 2, 8, 9, 7, 2, 9, 2, 5, 9, 0, 2],
      dtype=int64)

array([6, 2, 2, 2, 0, 9, 9, 2, 9, 2, 0, 7, 4, 8, 3, 2, 9, 2, 7, 9],
      dtype=int64)

array([2, 7, 6, 0, 2, 6, 9, 9, 9, 2, 2, 0, 2, 2, 5, 4, 2, 9, 2, 4],
      dtype=int64)

array([7, 2, 7, 2, 5, 0, 5, 2, 6, 2, 7, 3, 7, 9, 0, 7, 0, 3, 2, 9],
      dtype=int64)

array([7, 2, 2, 9, 9, 0, 2, 7, 6, 6, 5, 9, 1, 8, 6, 2, 7, 2, 9, 2],
      dtype=int64)

array([9, 2, 9, 7, 9, 8, 4, 3, 2, 4, 2, 9, 7, 7, 2, 2, 0, 3, 8, 8],
      dtype=int64)

array([9, 3, 5, 4, 1, 2, 7, 4, 3, 0, 0, 7, 2, 2, 9, 6, 1, 7, 2, 2],
      dtype=int64)

array([2, 9, 4, 9, 4, 2, 6, 6, 5, 7, 9, 8, 0, 8, 9, 2, 2, 0, 7, 0],
      dtype=int64)

array([3, 8, 9, 3, 9, 6, 2, 1, 5, 3, 9, 4, 7, 6, 6, 9, 9, 2, 7, 4],
      dtype=int64)

array([7, 9, 2, 2, 2, 9, 6, 2, 0, 7, 7, 3, 2, 4, 4, 2, 2, 2, 7, 6],
      dtype=int64)

array([6, 2, 4, 2, 5, 9, 3, 0, 5, 1, 4, 2, 6, 9, 2, 9, 1, 0, 2, 5],
      dtype=int64)

array([7, 2, 1, 9, 2, 9, 9, 2, 6, 2, 8, 8, 2, 2, 2, 9, 7, 3, 0, 7],
      dtype=int64)

array([5, 8, 3, 5, 2, 0, 0, 2, 9, 5, 0, 7, 2, 7, 6, 2, 2, 2, 7, 6],
      dtype=int64)

array([7, 2, 1, 2, 2, 9, 7, 9, 1, 4, 9, 8, 9, 7, 2, 8, 8, 2, 7, 0],
      dtype=int64)

array([0, 2, 5, 2, 6, 7, 7, 7, 9, 2, 1, 2, 9, 5, 7, 6, 2, 2, 9, 1],
      dtype=int64)

array([9, 2, 5, 2, 2, 7, 0, 1, 2, 7, 9, 9, 6, 8, 4, 5, 5, 0, 2, 9],
      dtype=int64)

array([5, 7, 9, 9, 2, 3, 9, 2, 2, 0, 2, 1, 9, 1, 6, 2, 6, 2, 7, 3],
      dtype=int64)

array([0, 2, 9, 5, 2, 4, 0, 3, 0, 4, 6, 3, 2, 2, 0, 7, 9, 9, 7, 1],
      dtype=int64)

array([2, 9, 6, 2, 6, 7, 9, 8, 2, 0, 2, 7, 6, 0, 0, 6, 2, 2, 2, 6],
      dtype=int64)

array([2, 2, 0, 9, 9, 0, 7, 7, 7, 6, 2, 5, 7, 7, 2, 8, 2, 5, 2, 7],
      dtype=int64)

array([0, 4, 0, 7, 6, 0, 2, 7, 2, 5, 5, 2, 2, 9, 2, 0, 2, 2, 6, 7],
      dtype=int64)

array([2, 2, 6, 5, 9, 8, 1, 6, 4, 2, 6, 6, 2, 2, 9, 1, 9, 8, 9, 9],
      dtype=int64)

array([9, 1, 2, 2, 7, 0, 2, 7, 8, 3, 7, 2, 9, 9, 6, 7, 2, 9, 5, 9],
      dtype=int64)

array([0, 9, 2, 2, 2, 2, 2, 7, 2, 5, 7, 2, 8, 9, 9, 5, 2, 7, 0, 9],
      dtype=int64)

array([2, 9, 3, 6, 7, 1, 5, 1, 9, 4, 2, 2, 6, 7, 2, 2, 8, 5, 7, 0],
      dtype=int64)

array([9, 6, 2, 5, 0, 7, 0, 8, 9, 4, 7, 7, 3, 1, 4, 3, 2, 5, 2, 3],
      dtype=int64)

array([9, 2, 7, 8, 9, 9, 2, 8, 5, 0, 7, 4, 4, 0, 9, 2, 2, 2, 8, 1],
      dtype=int64)

array([4, 0, 2, 2, 6, 2, 8, 7, 8, 2, 9, 2, 2, 6, 9, 2, 9, 9, 7, 3],
      dtype=int64)

array([4, 6, 7, 7, 2, 9, 6, 2, 2, 7, 2, 9, 3, 2, 0, 7, 0, 1, 2, 9],
      dtype=int64)

array([7, 3, 3, 4, 2, 9, 6, 5, 0, 2, 2, 4, 9, 3, 9, 9, 5, 9, 2, 7],
      dtype=int64)

array([7, 6, 7, 2, 7, 3, 2, 2, 2, 9, 5, 8, 2, 6, 3, 0, 9, 1, 1, 0],
      dtype=int64)

array([7, 3, 7, 7, 8, 3, 7, 2, 6, 2, 5, 5, 1, 2, 0, 4, 2, 9, 2, 8],
      dtype=int64)

array([7, 2, 2, 0, 2, 3, 4, 6, 8, 0, 9, 2, 2, 8, 9, 3, 0, 7, 2, 5],
      dtype=int64)

array([5, 2, 6, 7, 2, 2, 2, 9, 2, 9, 4, 4, 7, 4, 5, 5, 9, 1, 1, 2],
      dtype=int64)

array([2, 0, 9, 0, 4, 2, 4, 9, 0, 1, 1, 7, 4, 2, 2, 2, 2, 9, 7, 9],
      dtype=int64)

array([9, 7, 5, 9, 8, 6, 9, 0, 0, 5, 2, 2, 9, 2, 2, 9, 2, 2, 2, 9],
      dtype=int64)

array([9, 2, 0, 5, 8, 3, 9, 2, 0, 2, 9, 7, 6, 9, 9, 1, 1, 7, 2, 9],
      dtype=int64)

array([9, 8, 9, 2, 1, 7, 7, 0, 2, 5, 0, 6, 1, 9, 3, 6, 2, 2, 7, 9],
      dtype=int64)

array([2, 2, 7, 2, 7, 6, 0, 2, 2, 7, 0, 6, 2, 3, 4, 9, 9, 4, 3, 7],
      dtype=int64)

array([2, 6, 2, 6, 3, 7, 0, 0, 0, 2, 7, 9, 8, 9, 2, 9, 2, 2, 1, 2],
      dtype=int64)

array([2, 9, 2, 3, 5, 2, 9, 9, 8, 2, 7, 7, 5, 9, 4, 7, 7, 2, 8, 2],
      dtype=int64)

array([7, 2, 8, 0, 9, 3, 8, 2, 9, 0, 9, 8, 2, 2, 4, 0, 5, 2, 9, 1],
      dtype=int64)

array([2, 6, 7, 2, 2, 9, 9, 4, 1, 4, 3, 2, 6, 2, 4, 2, 9, 7, 5, 9],
      dtype=int64)

array([7, 2, 2, 2, 7, 9, 5, 4, 7, 7, 1, 7, 6, 4, 8, 2, 9, 2, 4, 9],
      dtype=int64)

array([5, 2, 0, 0, 1, 4, 6, 2, 4, 9, 3, 2, 5, 2, 1, 2, 1, 6, 0, 2],
      dtype=int64)

array([9, 2, 8, 0, 8, 9, 9, 3, 5, 2, 7, 9, 2, 0, 2, 3, 7, 2, 2, 1],
      dtype=int64)

array([7, 2, 2, 9, 9, 9, 8, 2, 2, 2, 2, 9, 1, 1, 9, 5, 9, 9, 1, 9],
      dtype=int64)

array([5, 0, 7, 0, 4, 2, 1, 7, 7, 9, 8, 6, 7, 2, 9, 4, 9, 7, 2, 2],
      dtype=int64)

array([2, 7, 1, 9, 9, 0, 1, 5, 6, 3, 2, 7, 7, 2, 2, 9, 3, 2, 9, 2],
      dtype=int64)

array([2, 2, 2, 0, 0, 0, 4, 7, 5, 1, 5, 2, 7, 9, 3, 7, 2, 2, 9, 2],
      dtype=int64)

array([2, 9, 0, 4, 9, 2, 0, 2, 2, 7, 2, 6, 5, 2, 0, 9, 4, 2, 4, 1],
      dtype=int64)

array([3, 5, 9, 2, 9, 7, 1, 9, 2, 8, 2, 2, 2, 1, 9, 2, 2, 7, 6, 9],
      dtype=int64)

array([2, 2, 0, 2, 9, 2, 1, 9, 8, 3, 7, 7, 2, 9, 5, 2, 5, 9, 9, 8],
      dtype=int64)

array([2, 2, 9, 2, 9, 9, 9, 1, 7, 7, 2, 6, 2, 2, 2, 2, 5, 5, 8, 9],
      dtype=int64)

array([2, 2, 7, 3, 7, 7, 2, 0, 5, 9, 0, 3, 9, 0, 2, 2, 4, 9, 6, 7],
      dtype=int64)

array([8, 9, 9, 6, 7, 2, 7, 4, 2, 8, 4, 5, 1, 6, 3, 7, 2, 7, 0, 2],
      dtype=int64)

array([6, 7, 2, 9, 5, 2, 8, 2, 7, 2, 3, 2, 7, 9, 9, 7, 0, 3, 9, 6],
      dtype=int64)

array([9, 2, 9, 4, 9, 2, 2, 2, 3, 7, 9, 2, 7, 9, 6, 7, 4, 3, 9, 8],
      dtype=int64)

array([9, 2, 3, 7, 7, 0, 9, 7, 2, 8, 9, 9, 5, 2, 2, 2, 2, 1, 7, 3],
      dtype=int64)

array([2, 7, 9, 9, 9, 7, 1, 9, 1, 1, 5, 2, 2, 3, 4, 9, 2, 9, 9, 2],
      dtype=int64)

array([9, 9, 5, 1, 9, 7, 2, 2, 2, 1, 2, 2, 4, 0, 8, 0, 6, 3, 8, 2],
      dtype=int64)

array([3, 0, 2, 2, 2, 1, 4, 4, 7, 0, 3, 3, 2, 9, 9, 9, 7, 9, 9, 1],
      dtype=int64)

array([3, 2, 2, 2, 9, 2, 9, 7, 7, 6, 7, 9, 5, 5, 8, 2, 6, 2, 2, 0],
      dtype=int64)

array([0, 7, 8, 2, 4, 0, 2, 3, 2, 4, 0, 9, 9, 6, 2, 5, 2, 6, 2, 9],
      dtype=int64)

array([2, 2, 2, 2, 2, 7, 7, 1, 3, 2, 2, 3, 6, 6, 1, 8, 2, 9, 6, 5],
      dtype=int64)

array([2, 0, 2, 7, 2, 7, 5, 6, 2, 4, 6, 7, 9, 6, 5, 2, 9, 4, 2, 0],
      dtype=int64)

array([2, 2, 2, 4, 9, 2, 7, 2, 5, 0, 0, 1, 1, 3, 2, 9, 6, 7, 0, 7],
      dtype=int64)

array([7, 6, 2, 8, 2, 2, 2, 2, 0, 9, 9, 9, 9, 2, 3, 0, 2, 6, 7, 4],
      dtype=int64)

array([2, 6, 6, 2, 9, 0, 2, 3, 0, 5, 2, 9, 2, 3, 7, 5, 9, 5, 1, 9],
      dtype=int64)

array([7, 6, 0, 2, 7, 2, 6, 7, 2, 5, 5, 9, 6, 0, 9, 6, 5, 2, 0, 0],
      dtype=int64)

array([6, 9, 2, 0, 9, 4, 2, 9, 2, 0, 5, 8, 0, 2, 9, 2, 0, 7, 2, 5],
      dtype=int64)

array([3, 5, 2, 9, 8, 0, 6, 2, 2, 7, 2, 5, 6, 7, 2, 8, 7, 2, 9, 2],
      dtype=int64)

array([9, 9, 2, 6, 6, 0, 0, 0, 2, 2, 2, 2, 2, 6, 5, 2, 9, 9, 7, 0],
      dtype=int64)

array([1, 4, 5, 7, 9, 9, 2, 5, 8, 7, 9, 9, 9, 3, 1, 1, 1, 0, 7, 7],
      dtype=int64)

array([9, 1, 9, 5, 8, 0, 8, 8, 6, 6, 9, 7, 2, 2, 7, 0, 5, 5, 2, 1],
      dtype=int64)

array([2, 0, 3, 7, 5, 2, 2, 2, 4, 2, 4, 2, 9, 9, 9, 9, 0, 0, 2, 9],
      dtype=int64)

array([7, 9, 2, 2, 9, 2, 5, 2, 7, 9, 0, 2, 9, 5, 7, 1, 2, 7, 0, 2],
      dtype=int64)

array([3, 2, 5, 2, 6, 9, 7, 0, 4, 9, 7, 9, 9, 7, 7, 6, 2, 3, 2, 2],
      dtype=int64)

array([2, 4, 2, 2, 2, 9, 7, 5, 9, 7, 5, 3, 2, 7, 8, 2, 9, 2, 9, 6],
      dtype=int64)

array([7, 2, 9, 8, 1, 7, 9, 9, 9, 8, 8, 2, 2, 2, 7, 2, 9, 9, 2, 3],
      dtype=int64)

array([7, 2, 7, 9, 7, 2, 2, 0, 2, 7, 5, 2, 2, 2, 3, 6, 9, 9, 4, 2],
      dtype=int64)

array([8, 9, 9, 9, 2, 9, 7, 1, 2, 7, 2, 2, 7, 2, 2, 2, 2, 6, 8, 7],
      dtype=int64)

array([9, 4, 1, 6, 0, 2, 5, 3, 3, 0, 0, 0, 6, 2, 6, 3, 2, 6, 2, 2],
      dtype=int64)

array([2, 7, 2, 9, 2, 9, 6, 2, 8, 6, 9, 7, 6, 8, 2, 2, 2, 0, 2, 7],
      dtype=int64)

array([3, 6, 2, 0, 8, 0, 7, 7, 2, 2, 5, 2, 4, 9, 2, 2, 7, 9, 7, 9],
      dtype=int64)

array([6, 4, 2, 1, 2, 8, 2, 9, 7, 9, 9, 5, 5, 2, 7, 6, 7, 5, 7, 4],
      dtype=int64)

array([9, 6, 7, 3, 8, 2, 0, 7, 3, 2, 1, 0, 9, 3, 4, 2, 2, 4, 7, 3],
      dtype=int64)

array([2, 9, 9, 6, 7, 7, 7, 7, 2, 2, 6, 8, 2, 9, 4, 2, 2, 5, 9, 2],
      dtype=int64)

array([2, 2, 6, 1, 7, 7, 8, 2, 3, 0, 5, 7, 5, 5, 8, 1, 2, 9, 9, 7],
      dtype=int64)

array([9, 2, 2, 6, 0, 7, 2, 3, 6, 7, 4, 0, 9, 7, 1, 0, 0, 6, 5, 1],
      dtype=int64)

array([9, 5, 0, 9, 4, 2, 2, 9, 7, 6, 7, 1, 0, 9, 7, 2, 2, 2, 6, 8],
      dtype=int64)

array([0, 1, 7, 2, 6, 2, 8, 2, 9, 5, 7, 4, 9, 4, 2, 4, 7, 6, 9, 9],
      dtype=int64)

array([5, 2, 9, 2, 9, 6, 0, 1, 7, 0, 2, 9, 3, 9, 7, 2, 2, 7, 9, 9],
      dtype=int64)

array([3, 9, 9, 4, 5, 2, 2, 0, 7, 9, 2, 7, 3, 9, 9, 2, 5, 1, 5, 3],
      dtype=int64)

array([7, 2, 7, 4, 9, 6, 2, 2, 7, 2, 9, 7, 0, 2, 2, 3, 9, 7, 6, 1],
      dtype=int64)

array([6, 2, 4, 5, 4, 1, 9, 3, 1, 9, 9, 9, 7, 1, 2, 4, 9, 2, 8, 9],
      dtype=int64)

array([7, 4, 9, 4, 6, 2, 2, 8, 5, 9, 7, 0, 9, 7, 3, 3, 3, 4, 2, 2],
      dtype=int64)

array([9, 7, 7, 6, 6, 2, 0, 9, 9, 5, 7, 2, 2, 2, 2, 4, 7, 7, 3, 1],
      dtype=int64)

array([0, 6, 6, 8, 2, 2, 5, 2, 2, 9, 5, 9, 6, 9, 0, 2, 7, 6, 2, 6],
      dtype=int64)

array([1, 0, 8, 8, 6, 9, 7, 1, 9, 2, 2, 9, 1, 7, 6, 3, 7, 7, 9, 9],
      dtype=int64)

array([8, 2, 6, 9, 7, 9, 5, 4, 2, 7, 7, 2, 0, 7, 6, 2, 4, 4, 2, 2],
      dtype=int64)

array([5, 5, 8, 7, 7, 2, 7, 0, 7, 4, 5, 2, 9, 2, 2, 9, 2, 9, 6, 6],
      dtype=int64)

array([5, 2, 9, 7, 9, 2, 9, 6, 9, 4, 2, 0, 2, 1, 9, 4, 9, 6, 2, 3],
      dtype=int64)

array([2, 1, 7, 4, 9, 6, 1, 2, 0, 7, 9, 4, 4, 3, 7, 2, 0, 7, 9, 2],
      dtype=int64)

array([6, 8, 6, 7, 2, 6, 8, 5, 2, 2, 2, 9, 2, 9, 2, 0, 8, 5, 0, 4],
      dtype=int64)

array([5, 9, 8, 7, 8, 2, 2, 2, 2, 0, 2, 2, 1, 7, 7, 2, 8, 4, 2, 9],
      dtype=int64)

array([8, 6, 0, 6, 2, 2, 3, 9, 2, 7, 9, 0, 2, 0, 3, 5, 2, 6, 4, 9],
      dtype=int64)

array([7, 2, 4, 3, 3, 9, 0, 2, 7, 7, 9, 4, 5, 6, 2, 2, 7, 1, 9, 2],
      dtype=int64)

array([8, 7, 2, 8, 3, 7, 4, 2, 8, 7, 6, 2, 0, 2, 7, 9, 9, 2, 4, 9],
      dtype=int64)

array([9, 2, 2, 5, 2, 8, 2, 7, 5, 4, 2, 2, 9, 9, 5, 9, 2, 2, 2, 0],
      dtype=int64)

array([4, 3, 9, 3, 9, 2, 2, 2, 7, 2, 8, 9, 2, 5, 9, 2, 9, 6, 7, 6],
      dtype=int64)

array([0, 9, 5, 2, 9, 2, 9, 7, 2, 2, 2, 8, 3, 2, 9, 2, 7, 7, 4, 7],
      dtype=int64)

array([9, 2, 2, 2, 9, 2, 1, 7, 9, 9, 2, 9, 2, 9, 2, 1, 2, 9, 6, 5],
      dtype=int64)

array([7, 7, 2, 9, 0, 9, 1, 9, 4, 4, 5, 7, 0, 1, 5, 9, 2, 6, 3, 2],
      dtype=int64)

array([1, 7, 7, 3, 0, 7, 9, 7, 1, 0, 9, 5, 9, 2, 2, 2, 2, 2, 9, 9],
      dtype=int64)

array([3, 3, 2, 5, 0, 5, 6, 2, 7, 4, 8, 2, 3, 9, 2, 2, 4, 9, 2, 2],
      dtype=int64)

array([3, 7, 8, 2, 7, 9, 2, 2, 2, 2, 6, 2, 2, 9, 6, 8, 4, 2, 9, 9],
      dtype=int64)

array([5, 7, 5, 9, 7, 2, 2, 7, 2, 2, 6, 2, 0, 0, 3, 1, 2, 2, 1, 3],
      dtype=int64)

array([2, 7, 7, 5, 3, 9, 7, 2, 0, 4, 2, 9, 9, 2, 6, 6, 2, 2, 0, 2],
      dtype=int64)

array([7, 4, 9, 9, 8, 0, 0, 2, 2, 9, 6, 3, 2, 9, 8, 1, 2, 4, 7, 7],
      dtype=int64)

array([9, 9, 7, 2, 4, 4, 8, 2, 0, 7, 0, 6, 9, 5, 7, 5, 2, 2, 2, 2],
      dtype=int64)

array([6, 9, 9, 2, 2, 9, 9, 9, 0, 2, 7, 7, 2, 2, 2, 3, 8, 7, 5, 7],
      dtype=int64)

array([0, 5, 6, 2, 3, 2, 7, 5, 4, 4, 5, 9, 2, 2, 7, 1, 1, 6, 0, 8],
      dtype=int64)

array([2, 2, 8, 7, 6, 4, 7, 3, 8, 4, 2, 2, 9, 7, 7, 8, 2, 5, 2, 2],
      dtype=int64)

array([8, 5, 7, 2, 7, 2, 2, 7, 2, 5, 2, 2, 0, 7, 2, 5, 7, 5, 2, 2],
      dtype=int64)

array([2, 6, 8, 1, 9, 9, 2, 3, 4, 5, 6, 2, 1, 1, 3, 7, 9, 3, 6, 6],
      dtype=int64)

array([7, 2, 7, 2, 9, 2, 9, 7, 9, 7, 8, 9, 2, 1, 2, 2, 7, 0, 6, 6],
      dtype=int64)

array([2, 3, 7, 7, 4, 9, 0, 7, 3, 4, 1, 5, 1, 2, 9, 2, 3, 2, 5, 0],
      dtype=int64)

array([8, 2, 8, 0, 9, 3, 9, 6, 2, 9, 2, 2, 2, 1, 3, 9, 7, 6, 7, 2],
      dtype=int64)

array([5, 0, 9, 2, 2, 7, 2, 5, 7, 2, 8, 2, 9, 9, 2, 4, 8, 9, 7, 8],
      dtype=int64)

array([2, 5, 9, 2, 2, 3, 4, 7, 7, 9, 3, 5, 9, 7, 7, 7, 8, 7, 8, 1],
      dtype=int64)

array([2, 8, 5, 0, 4, 3, 2, 7, 9, 6, 6, 8, 9, 3, 6, 9, 2, 7, 2, 2],
      dtype=int64)

array([4, 3, 0, 0, 5, 3, 4, 6, 2, 7, 0, 9, 2, 2, 6, 5, 9, 2, 2, 7],
      dtype=int64)

array([2, 5, 8, 9, 5, 7, 8, 2, 9, 1, 0, 4, 9, 4, 7, 6, 2, 2, 3, 6],
      dtype=int64)

array([7, 2, 7, 9, 1, 2, 7, 8, 9, 3, 0, 2, 8, 7, 2, 9, 4, 9, 9, 7],
      dtype=int64)

array([2, 9, 6, 2, 1, 7, 7, 2, 2, 0, 9, 0, 0, 9, 2, 6, 5, 3, 4, 2],
      dtype=int64)

array([7, 2, 9, 6, 9, 8, 7, 2, 0, 2, 5, 6, 7, 2, 2, 9, 2, 9, 5, 3],
      dtype=int64)

array([4, 2, 7, 0, 0, 9, 1, 2, 0, 2, 3, 2, 4, 7, 6, 3, 7, 7, 5, 0],
      dtype=int64)

array([9, 6, 1, 9, 5, 2, 0, 1, 7, 6, 4, 0, 2, 9, 1, 1, 9, 9, 7, 2],
      dtype=int64)

array([6, 9, 9, 2, 2, 2, 7, 1, 5, 5, 8, 0, 6, 2, 9, 9, 8, 2, 4, 0],
      dtype=int64)

array([2, 5, 5, 3, 2, 7, 4, 2, 5, 8, 3, 2, 7, 7, 1, 0, 7, 1, 9, 2],
      dtype=int64)

array([2, 2, 8, 2, 0, 9, 9, 7, 9, 0, 2, 7, 7, 1, 2, 9, 0, 2, 2, 3],
      dtype=int64)

array([9, 2, 1, 2, 2, 9, 7, 9, 2, 9, 5, 9, 8, 2, 2, 2, 9, 6, 5, 2],
      dtype=int64)

array([7, 7, 5, 9, 2, 3, 9, 9, 2, 2, 7, 2, 6, 2, 8, 2, 2, 9, 0, 2],
      dtype=int64)

array([2, 0, 4, 9, 9, 6, 9, 4, 4, 2, 5, 1, 6, 9, 1, 9, 6, 7, 3, 1],
      dtype=int64)

array([0, 2, 4, 9, 2, 9, 0, 2, 8, 9, 5, 7, 9, 0, 2, 0, 2, 7, 2, 6],
      dtype=int64)

array([4, 3, 5, 1, 7, 8, 8, 2, 6, 2, 2, 2, 5, 0, 8, 2, 4, 6, 7, 2],
      dtype=int64)

array([2, 3, 0, 2, 1, 9, 9, 9, 7, 2, 4, 2, 7, 8, 6, 2, 7, 1, 7, 2],
      dtype=int64)

array([2, 8, 9, 2, 1, 7, 9, 0, 9, 3, 7, 4, 2, 9, 8, 2, 5, 1, 9, 1],
      dtype=int64)

array([2, 2, 9, 6, 2, 2, 7, 2, 7, 9, 9, 8, 6, 8, 1, 5, 2, 1, 2, 7],
      dtype=int64)

array([9, 9, 9, 2, 5, 1, 1, 5, 2, 4, 1, 9, 2, 2, 7, 7, 6, 3, 4, 6],
      dtype=int64)

array([2, 7, 6, 8, 4, 2, 0, 9, 7, 9, 2, 5, 9, 2, 7, 2, 2, 2, 2, 4],
      dtype=int64)

array([6, 6, 4, 2, 9, 2, 1, 5, 9, 8, 2, 5, 4, 2, 5, 0, 7, 2, 9, 9],
      dtype=int64)

array([2, 0, 9, 2, 3, 4, 2, 4, 1, 2, 9, 6, 5, 5, 2, 7, 9, 5, 1, 5],
      dtype=int64)

array([8, 1, 2, 9, 5, 2, 2, 7, 5, 5, 5, 6, 9, 2, 5, 0, 0, 0, 6, 7],
      dtype=int64)

array([0, 7, 2, 9, 9, 9, 9, 2, 2, 2, 7, 9, 2, 2, 7, 1, 9, 2, 4, 4],
      dtype=int64)

array([2, 1, 0, 9, 5, 9, 1, 7, 0, 5, 0, 4, 7, 7, 3, 3, 8, 9, 6, 1],
      dtype=int64)

array([9, 2, 2, 5, 2, 2, 9, 2, 2, 9, 2, 2, 3, 2, 6, 8, 3, 7, 8, 8],
      dtype=int64)

array([6, 5, 9, 8, 7, 0, 2, 0, 3, 2, 2, 0, 2, 2, 2, 6, 7, 4, 7, 4],
      dtype=int64)

array([9, 7, 5, 3, 9, 2, 2, 0, 9, 9, 2, 2, 7, 9, 2, 3, 8, 9, 7, 7],
      dtype=int64)

array([0, 2, 9, 5, 2, 6, 1, 9, 3, 7, 7, 8, 6, 2, 7, 4, 9, 9, 5, 2],
      dtype=int64)

array([5, 9, 9, 9, 2, 9, 8, 9, 3, 6, 5, 2, 1, 4, 2, 9, 2, 4, 2, 4],
      dtype=int64)

array([4, 8, 5, 2, 5, 7, 6, 2, 6, 2, 2, 0, 9, 2, 2, 2, 7, 7, 9, 2],
      dtype=int64)

array([2, 7, 2, 6, 7, 7, 2, 3, 2, 8, 2, 7, 6, 3, 4, 3, 9, 9, 2, 9],
      dtype=int64)

array([0, 7, 6, 8, 7, 2, 2, 4, 9, 9, 2, 4, 8, 2, 2, 2, 3, 7, 2, 6],
      dtype=int64)

array([2, 7, 3, 7, 2, 9, 2, 5, 9, 0, 4, 1, 6, 3, 0, 6, 9, 2, 9, 3],
      dtype=int64)

array([9, 4, 7, 9, 7, 1, 2, 8, 3, 2, 4, 4, 6, 5, 2, 2, 6, 1, 7, 9],
      dtype=int64)

array([4, 7, 6, 1, 2, 1, 5, 1, 1, 5, 2, 5, 4, 6, 4, 1, 9, 5, 2, 9],
      dtype=int64)

array([0, 5, 9, 7, 5, 8, 6, 3, 6, 3, 2, 2, 2, 9, 9, 3, 2, 0, 7, 0],
      dtype=int64)

array([9, 4, 2, 2, 1, 8, 7, 2, 6, 7, 9, 2, 2, 8, 3, 3, 8, 2, 8, 4],
      dtype=int64)

array([3, 2, 7, 2, 2, 4, 3, 6, 2, 8, 8, 9, 2, 6, 2, 9, 6, 3, 1, 2],
      dtype=int64)

array([2, 0, 2, 2, 2, 7, 7, 8, 6, 6, 9, 2, 4, 6, 2, 1, 7, 9, 9, 9],
      dtype=int64)

array([2, 7, 9, 2, 6, 5, 9, 8, 5, 6, 2, 5, 8, 2, 2, 6, 0, 7, 6, 5],
      dtype=int64)

array([8, 2, 8, 9, 8, 7, 8, 9, 2, 9, 2, 6, 1, 2, 2, 2, 6, 9, 2, 2],
      dtype=int64)

array([3, 2, 9, 7, 0, 9, 9, 7, 6, 2, 4, 9, 7, 2, 7, 1, 6, 4, 2, 1],
      dtype=int64)

array([0, 2, 5, 2, 3, 6, 2, 5, 2, 9, 4, 2, 7, 9, 2, 0, 9, 2, 7, 0],
      dtype=int64)

array([5, 3, 5, 2, 2, 7, 2, 4, 6, 2, 9, 7, 5, 7, 2, 0, 7, 7, 7, 1],
      dtype=int64)

array([2, 9, 5, 8, 2, 9, 2, 0, 2, 6, 0, 3, 2, 9, 4, 2, 9, 6, 6, 2],
      dtype=int64)

array([4, 8, 2, 8, 6, 2, 5, 2, 0, 9, 3, 3, 2, 1, 9, 6, 0, 4, 9, 3],
      dtype=int64)

array([3, 9, 8, 2, 2, 5, 2, 2, 0, 9, 6, 3, 1, 9, 0, 6, 4, 1, 9, 9],
      dtype=int64)

array([9, 7, 2, 7, 6, 5, 2, 8, 2, 9, 2, 5, 2, 0, 2, 9, 7, 8, 2, 9],
      dtype=int64)

array([6, 4, 2, 9, 4, 0, 5, 2, 6, 8, 7, 9, 7, 9, 8, 4, 2, 2, 2, 9],
      dtype=int64)

array([2, 4, 2, 7, 3, 2, 9, 7, 7, 0, 0, 6, 2, 0, 0, 9, 9, 9, 5, 2],
      dtype=int64)

array([2, 9, 9, 2, 2, 6, 4, 4, 9, 8, 6, 2, 2, 6, 2, 9, 8, 5, 9, 5],
      dtype=int64)

array([2, 2, 2, 2, 5, 0, 2, 2, 0, 5, 9, 5, 9, 2, 2, 9, 7, 5, 7, 6],
      dtype=int64)

array([6, 2, 7, 5, 9, 6, 0, 2, 4, 7, 4, 6, 1, 0, 6, 2, 2, 5, 2, 2],
      dtype=int64)

array([2, 3, 9, 8, 7, 0, 9, 2, 6, 2, 9, 4, 2, 7, 5, 2, 9, 3, 8, 6],
      dtype=int64)

array([7, 2, 3, 8, 5, 2, 7, 8, 0, 2, 9, 7, 4, 2, 1, 6, 5, 2, 2, 9],
      dtype=int64)

array([7, 6, 2, 1, 2, 4, 2, 2, 9, 9, 2, 7, 5, 6, 2, 3, 9, 2, 9, 1],
      dtype=int64)

array([8, 5, 9, 3, 7, 2, 1, 9, 2, 2, 7, 6, 7, 5, 9, 0, 6, 5, 7, 7],
      dtype=int64)

array([2, 8, 5, 7, 9, 9, 4, 2, 6, 2, 3, 9, 9, 9, 9, 1, 9, 2, 6, 9],
      dtype=int64)

array([7, 9, 7, 2, 9, 3, 2, 6, 2, 9, 6, 2, 9, 3, 2, 2, 9, 9, 3, 9],
      dtype=int64)

array([7, 7, 0, 3, 0, 9, 2, 2, 3, 2, 7, 2, 2, 9, 0, 2, 3, 7, 2, 8],
      dtype=int64)

array([7, 6, 6, 2, 1, 9, 6, 9, 0, 8, 2, 7, 9, 2, 0, 4, 2, 6, 9, 2],
      dtype=int64)

array([0, 9, 9, 2, 2, 0, 2, 9, 2, 2, 9, 9, 2, 7, 6, 8, 6, 2, 9, 1],
      dtype=int64)

array([2, 0, 4, 7, 0, 2, 0, 1, 8, 3, 0, 6, 6, 7, 2, 1, 9, 4, 1, 2],
      dtype=int64)

array([9, 9, 6, 0, 2, 7, 7, 7, 4, 2, 3, 7, 2, 2, 7, 2, 2, 2, 8, 6],
      dtype=int64)

array([2, 7, 9, 2, 5, 2, 2, 9, 2, 9, 2, 5, 7, 5, 8, 8, 7, 5, 9, 1],
      dtype=int64)

array([9, 9, 2, 7, 2, 2, 4, 3, 3, 7, 6, 3, 2, 0, 2, 5, 7, 2, 0, 2],
      dtype=int64)

array([9, 9, 3, 1, 7, 9, 2, 5, 9, 2, 0, 3, 0, 4, 6, 0, 2, 2, 2, 7],
      dtype=int64)

array([2, 4, 2, 3, 9, 6, 6, 7, 1, 9, 0, 2, 5, 3, 4, 2, 9, 6, 7, 9],
      dtype=int64)

array([2, 9, 9, 0, 9, 2, 2, 0, 8, 7, 4, 0, 9, 2, 9, 5, 6, 2, 8, 2],
      dtype=int64)

array([0, 2, 2, 9, 9, 3, 4, 3, 8, 4, 7, 6, 5, 3, 2, 7, 9, 0, 7, 2],
      dtype=int64)

array([2, 2, 5, 2, 9, 8, 6, 0, 2, 2, 9, 5, 3, 7, 4, 3, 7, 0, 2, 6],
      dtype=int64)

array([6, 1, 7, 5, 2, 6, 2, 7, 0, 2, 5, 0, 3, 6, 0, 2, 3, 8, 2, 7],
      dtype=int64)

array([3, 2, 1, 2, 2, 7, 7, 8, 0, 7, 9, 4, 9, 2, 2, 9, 3, 2, 9, 2],
      dtype=int64)

array([6, 7, 9, 9, 8, 0, 0, 2, 9, 2, 6, 2, 7, 8, 2, 3, 0, 7, 9, 1],
      dtype=int64)

array([9, 4, 9, 3, 2, 9, 9, 4, 3, 1, 9, 2, 2, 2, 3, 3, 7, 2, 6, 9],
      dtype=int64)

array([2, 0, 7, 9, 8, 4, 2, 2, 2, 2, 5, 7, 9, 9, 2, 3, 2, 9, 7, 1],
      dtype=int64)

array([5, 2, 8, 1, 2, 7, 2, 8, 7, 8, 5, 1, 9, 5, 2, 9, 7, 7, 4, 2],
      dtype=int64)

array([2, 4, 6, 2, 9, 4, 7, 8, 3, 0, 6, 2, 8, 6, 7, 2, 2, 9, 2, 9],
      dtype=int64)

array([1, 9, 4, 9, 9, 5, 2, 9, 6, 6, 5, 9, 2, 1, 1, 7, 0, 7, 5, 4],
      dtype=int64)

array([2, 7, 2, 2, 9, 6, 6, 8, 2, 7, 9, 2, 2, 3, 2, 0, 2, 2, 7, 8],
      dtype=int64)

array([9, 6, 2, 1, 2, 9, 9, 7, 3, 1, 8, 9, 0, 1, 4, 6, 9, 2, 3, 2],
      dtype=int64)

array([7, 1, 8, 7, 6, 2, 5, 6, 7, 2, 2, 5, 2, 2, 9, 7, 2, 2, 3, 9],
      dtype=int64)

array([0, 9, 0, 9, 2, 9, 2, 7, 2, 4, 9, 2, 1, 4, 5, 6, 7, 2, 5, 0],
      dtype=int64)

array([0, 1, 5, 9, 2, 1, 2, 7, 5, 3, 4, 4, 4, 9, 7, 2, 2, 7, 8, 9],
      dtype=int64)

array([4, 1, 1, 6, 2, 2, 8, 9, 7, 2, 9, 9, 3, 9, 8, 7, 1, 2, 9, 3],
      dtype=int64)

array([2, 9, 0, 2, 4, 9, 3, 9, 5, 6, 9, 0, 2, 7, 8, 2, 2, 2, 9, 2],
      dtype=int64)

array([2, 2, 7, 6, 2, 2, 9, 4, 1, 8, 4, 4, 2, 9, 9, 7, 0, 0, 9, 7],
      dtype=int64)

array([4, 9, 7, 7, 1, 2, 2, 2, 8, 4, 2, 2, 2, 3, 2, 9, 9, 2, 0, 8],
      dtype=int64)

array([9, 6, 2, 5, 3, 5, 2, 2, 8, 2, 9, 1, 7, 0, 2, 7, 7, 2, 2, 0],
      dtype=int64)

array([9, 2, 9, 2, 2, 6, 2, 7, 6, 8, 7, 5, 7, 7, 5, 2, 2, 7, 1, 4],
      dtype=int64)

array([7, 2, 8, 2, 7, 7, 2, 9, 9, 2, 4, 3, 5, 6, 0, 6, 1, 7, 0, 2],
      dtype=int64)

array([9, 2, 1, 9, 2, 9, 7, 7, 9, 3, 0, 9, 7, 0, 2, 2, 2, 9, 2, 4],
      dtype=int64)

array([3, 9, 7, 2, 2, 3, 0, 5, 2, 7, 7, 7, 9, 5, 2, 5, 1, 2, 0, 2],
      dtype=int64)

array([7, 2, 6, 4, 2, 9, 2, 9, 6, 2, 4, 5, 0, 8, 2, 6, 7, 2, 0, 2],
      dtype=int64)

array([2, 2, 2, 7, 0, 2, 2, 9, 9, 2, 1, 7, 7, 2, 4, 0, 2, 8, 7, 7],
      dtype=int64)

array([8, 2, 2, 5, 0, 3, 2, 2, 2, 7, 2, 9, 1, 4, 2, 2, 6, 7, 3, 9],
      dtype=int64)

array([0, 9, 5, 9, 7, 4, 2, 2, 2, 4, 4, 7, 2, 9, 2, 2, 3, 9, 9, 4],
      dtype=int64)

array([2, 9, 1, 2, 0, 2, 2, 7, 2, 5, 5, 2, 5, 0, 6, 4, 7, 9, 6, 6],
      dtype=int64)

array([1, 3, 2, 6, 7, 4, 9, 5, 4, 1, 7, 3, 9, 2, 6, 3, 6, 2, 9, 2],
      dtype=int64)

array([6, 4, 2, 2, 0, 8, 2, 7, 6, 9, 7, 2, 2, 9, 2, 4, 2, 9, 2, 9],
      dtype=int64)

array([4, 2, 3, 2, 9, 5, 5, 7, 2, 0, 4, 6, 1, 9, 3, 2, 7, 1, 5, 2],
      dtype=int64)

array([9, 1, 7, 2, 2, 1, 7, 5, 2, 9, 9, 5, 2, 9, 6, 2, 6, 7, 7, 0],
      dtype=int64)

array([2, 9, 8, 9, 3, 7, 2, 1, 2, 2, 4, 2, 5, 7, 6, 3, 2, 8, 5, 2],
      dtype=int64)

array([5, 9, 7, 2, 6, 6, 6, 4, 2, 3, 3, 0, 1, 1, 0, 2, 9, 0, 4, 2],
      dtype=int64)

array([2, 9, 4, 7, 0, 7, 4, 2, 2, 2, 6, 2, 0, 3, 9, 3, 8, 5, 7, 2],
      dtype=int64)

array([2, 7, 2, 3, 7, 1, 6, 7, 0, 5, 2, 2, 5, 4, 9, 9, 9, 2, 9, 2],
      dtype=int64)

array([9, 0, 9, 2, 1, 9, 4, 6, 6, 7, 2, 0, 9, 2, 3, 9, 9, 2, 9, 1],
      dtype=int64)

array([1, 9, 9, 2, 5, 6, 9, 6, 8, 2, 2, 2, 2, 6, 9, 8, 2, 7, 2, 0],
      dtype=int64)

array([5, 4, 0, 9, 0, 2, 6, 9, 0, 1, 9, 6, 7, 2, 2, 2, 7, 2, 2, 8],
      dtype=int64)

array([8, 9, 8, 7, 4, 2, 2, 6, 2, 4, 6, 3, 4, 9, 2, 2, 3, 9, 3, 9],
      dtype=int64)

array([9, 6, 9, 4, 9, 6, 2, 9, 3, 4, 2, 2, 2, 1, 7, 2, 8, 2, 2, 0],
      dtype=int64)

array([8, 9, 9, 3, 7, 2, 9, 6, 7, 2, 2, 0, 2, 2, 9, 0, 9, 9, 2, 5],
      dtype=int64)

array([2, 9, 1, 9, 2, 2, 9, 5, 2, 7, 7, 0, 7, 0, 7, 9, 2, 2, 1, 3],
      dtype=int64)

array([5, 9, 5, 2, 9, 2, 2, 9, 9, 2, 2, 0, 9, 7, 2, 1, 0, 9, 2, 6],
      dtype=int64)

array([1, 5, 9, 2, 7, 0, 1, 2, 0, 8, 7, 7, 7, 9, 2, 1, 9, 6, 4, 9],
      dtype=int64)

array([5, 7, 9, 9, 2, 6, 9, 0, 9, 2, 2, 9, 0, 0, 2, 2, 2, 9, 1, 2],
      dtype=int64)

array([7, 2, 9, 4, 7, 4, 5, 7, 9, 2, 2, 1, 2, 9, 2, 3, 5, 2, 9, 0],
      dtype=int64)

array([2, 2, 2, 9, 9, 8, 2, 3, 0, 5, 9, 6, 2, 1, 9, 7, 2, 5, 9, 9],
      dtype=int64)

array([8, 5, 7, 5, 2, 3, 9, 2, 0, 2, 2, 2, 2, 9, 9, 9, 0, 9, 7, 7],
      dtype=int64)

array([9, 7, 9, 2, 8, 1, 5, 4, 0, 7, 7, 0, 7, 5, 9, 3, 1, 2, 9, 2],
      dtype=int64)

array([1, 2, 2, 4, 2, 8, 7, 3, 4, 2, 9, 9, 9, 2, 7, 9, 5, 0, 7, 2],
      dtype=int64)

Loss: 2.302849, Train accuracy: 0.110333, val accuracy: 0.111000


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

Loss: 2.302628, Train accuracy: 0.066333, val accuracy: 0.049000


KeyboardInterrupt: 

In [ ]:
plt.plot(train_history)
plt.plot(val_history)

# Улучшаем процесс тренировки

Мы реализуем несколько ключевых оптимизаций, необходимых для тренировки современных нейросетей.

## Уменьшение скорости обучения (learning rate decay)

Одна из необходимых оптимизаций во время тренировки нейронных сетей - постепенное уменьшение скорости обучения по мере тренировки.

Один из стандартных методов - уменьшение скорости обучения (learning rate) каждые N эпох на коэффициент d (часто называемый decay). Значения N и d, как всегда, являются гиперпараметрами и должны подбираться на основе эффективности на проверочных данных (validation data). 

В нашем случае N будет равным 1.

In [ ]:
# TODO Implement learning rate decay inside Trainer.fit method
# Decay should happen once per epoch

model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 100, reg = 1e-1)
dataset = Dataset(train_X, train_y, val_X, val_y)
trainer = Trainer(model, dataset, SGD(), learning_rate_decay=0.99)

initial_learning_rate = trainer.learning_rate
loss_history, train_history, val_history = trainer.fit()

assert trainer.learning_rate < initial_learning_rate, "Learning rate should've been reduced"
assert trainer.learning_rate > 0.5*initial_learning_rate, "Learning rate shouldn'tve been reduced that much!"

# Накопление импульса (Momentum SGD)

Другой большой класс оптимизаций - использование более эффективных методов градиентного спуска. Мы реализуем один из них - накопление импульса (Momentum SGD).

Этот метод хранит скорость движения, использует градиент для ее изменения на каждом шаге, и изменяет веса пропорционально значению скорости.
(Физическая аналогия: Вместо скорости градиенты теперь будут задавать ускорение, но будет присутствовать сила трения.)

```
velocity = momentum * velocity - learning_rate * gradient 
w = w + velocity
```

`momentum` здесь коэффициент затухания, который тоже является гиперпараметром (к счастью, для него часто есть хорошее значение по умолчанию, типичный диапазон -- 0.8-0.99).

Несколько полезных ссылок, где метод разбирается более подробно:  
http://cs231n.github.io/neural-networks-3/#sgd  
https://distill.pub/2017/momentum/

In [ ]:
# TODO: Implement MomentumSGD.update function in optim.py

model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 100, reg = 1e-1)
dataset = Dataset(train_X, train_y, val_X, val_y)
trainer = Trainer(model, dataset, MomentumSGD(), learning_rate=1e-4, learning_rate_decay=0.99)

# You should see even better results than before!
loss_history, train_history, val_history = trainer.fit()

# Ну что, давайте уже тренировать сеть!

## Последний тест - переобучимся (overfit) на маленьком наборе данных

Хороший способ проверить, все ли реализовано корректно - переобучить сеть на маленьком наборе данных.  
Наша модель обладает достаточной мощностью, чтобы приблизить маленький набор данных идеально, поэтому мы ожидаем, что на нем мы быстро дойдем до 100% точности на тренировочном наборе. 

Если этого не происходит, то где-то была допущена ошибка!

In [ ]:
data_size = 15
model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 100, reg = 1e-1)
dataset = Dataset(train_X[:data_size], train_y[:data_size], val_X[:data_size], val_y[:data_size])
trainer = Trainer(model, dataset, SGD(), learning_rate=1e-1, num_epochs=150, batch_size=5)

# You should expect this to reach 1.0 training accuracy 
loss_history, train_history, val_history = trainer.fit()

Теперь найдем гипепараметры, для которых этот процесс сходится быстрее.
Если все реализовано корректно, то существуют параметры, при которых процесс сходится в **20** эпох или еще быстрее.
Найдите их!

In [ ]:
# Now, tweak some hyper parameters and make it train to 1.0 accuracy in 20 epochs or less

model = TwoLayerNet(n_input = train_X.shape[1], n_output = 10, hidden_layer_size = 100, reg = 1e-1)
dataset = Dataset(train_X[:data_size], train_y[:data_size], val_X[:data_size], val_y[:data_size])
# TODO: Change any hyperparamers or optimizators to reach training accuracy in 20 epochs
trainer = Trainer(model, dataset, SGD(), learning_rate=1e-1, num_epochs=20, batch_size=5)

loss_history, train_history, val_history = trainer.fit()

# Итак, основное мероприятие!

Натренируйте лучшую нейросеть! Можно добавлять и изменять параметры, менять количество нейронов в слоях сети и как угодно экспериментировать. 

Добейтесь точности лучше **40%** на validation set.

In [ ]:
# Let's train the best one-hidden-layer network we can

learning_rates = 1e-4
reg_strength = 1e-3
learning_rate_decay = 0.999
hidden_layer_size = 128
num_epochs = 200
batch_size = 64

best_classifier = None
best_val_accuracy = None

loss_history = []
train_history = []
val_history = []

# TODO find the best hyperparameters to train the network
# Don't hesitate to add new values to the arrays above, perform experiments, use any tricks you want
# You should expect to get to at least 40% of valudation accuracy
# Save loss/train/history of the best classifier to the variables above

print('best validation accuracy achieved: %f' % best_val_accuracy)

In [ ]:
plt.figure(figsize=(15, 7))
plt.subplot(211)
plt.title("Loss")
plt.plot(loss_history)
plt.subplot(212)
plt.title("Train/validation accuracy")
plt.plot(train_history)
plt.plot(val_history)

# Как обычно, посмотрим, как наша лучшая модель работает на тестовых данных

In [ ]:
test_pred = best_classifier.predict(test_X)
test_accuracy = multiclass_accuracy(test_pred, test_y)
print('Neural net test set accuracy: %f' % (test_accuracy, ))